### ISSUE TITLE
Error on installing gcc-tdm w/ scoop command

### ISSUE THREAD

**Issue by Tee0125** [rivy/PCRE#1]
gcc-tdm package might be renamed to gcc@5.1.0-tdm, but 'Building procedure' is not updated. So scoop command failed to install gcc-tdm

**Comment by rivy** [comment]
Thanks.

I'll look at it and update the README.

**Comment by rivy** [comment]
@Tee0125 , I rewrote and tested the build instructions. I believe they are now up to date. Just let me know if you have any more problems.
